// <auto-generated />
namespace DomainCore.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class add_class_user_messages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_class_user_messages));
        
        string IMigrationMetadata.Id
        {
            get { return "201303041800216_add_class_user_messages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
