// <auto-generated />
namespace DomainCore.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Add_class_State_Messages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_class_State_Messages));
        
        string IMigrationMetadata.Id
        {
            get { return "201304140609236_Add_class_State_Messages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
