// <auto-generated />
namespace DomainCore.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Set_Message_Content_Length_ToMax : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Set_Message_Content_Length_ToMax));
        
        string IMigrationMetadata.Id
        {
            get { return "201304171552073_Set_Message_Content_Length_To-Max"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
