// <auto-generated />
namespace DomainCore.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Add_MessageType_Into_Message_Class : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_MessageType_Into_Message_Class));
        
        string IMigrationMetadata.Id
        {
            get { return "201304171531170_Add_MessageType_Into_Message_Class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
