// <auto-generated />
namespace DomainCore.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class update_ChineseLastname_class : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_ChineseLastname_class));
        
        string IMigrationMetadata.Id
        {
            get { return "201303041714458_update_ChineseLastname_class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
