// <auto-generated />
namespace DomainCore.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Set_StateMessage_Content_Length : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Set_StateMessage_Content_Length));
        
        string IMigrationMetadata.Id
        {
            get { return "201304151513003_Set_StateMessage_Content_Length"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
